name: Build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller 
          pip install -r requirements.txt
      - name: Build
        run: pyinstaller obs_manager/GUI/__main__.py --name "${{matrix.os}}-Manager" --windowed --i obs_manager/GUI/hand.ico --noconfirm --add-data 'obs_manager/GUI/*;obs_manager/GUI' --distpath app
      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: app/${{ matrix.os }}-Manager
          if-no-files-found: error
